language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  # - COMPOSER_ROOT_VERSION is needed to get round the recursive dependency when using CI.
  - export COMPOSER_ROOT_VERSION="3.99.99"
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
